server:
  port: ${AUTH_SERVICE_PORT:8101}

spring:
  application:
    name: auth-service
  config:
    import:
      - optional:nacos:${spring.application.name}.yaml?refreshEnabled=true
  cloud:
    nacos:
      server-addr: ${NACOS_SERVER_ADDR:127.0.0.1:8848}
      username: ${NACOS_USERNAME:nacos}
      password: ${NACOS_PASSWORD:nacos}
      discovery:
        namespace: ${NACOS_NAMESPACE:public}
      config:
        namespace: ${NACOS_NAMESPACE:public}
    sentinel:
      eager: ${SENTINEL_EAGER:true}
      transport:
        dashboard: ${SENTINEL_DASHBOARD:127.0.0.1:8858}
        port: ${SENTINEL_TRANSPORT_PORT:8719}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      probes:
        enabled: true
